DELETE http://localhost:3001/api/blogs/65f6f63f43a7f96a1fa9f129
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBla2thbmVuIiwiaWQiOiI2NWY2MDYwODE5NzQ0NjU3YTNkOGJmYjciLCJpYXQiOjE3MTA2ODI1Mzd9.Bg3bA-nfRBA6AYXlEr-M4l4_K_NAg2ToPcAYmwsvJsE
